### ISSUE TITLE
SelectFormField在默认的时候去会请求一次，建议变成可配的

### ISSUE THREAD

**Issue by fengsx** [uxcore/uxcore-select-form-field#4]
现在的SelectFormField在默认的时候去会请求一次，建议变成可配的。而且比较好的交互是，输入框获取焦点的时候去请求一次，而不是说在页面初始化的时候再去请求的。

![image](https://cloud.githubusercontent.com/assets/7709602/23394893/9a4eb988-fdc6-11e6-81f4-1a3d6000ff66.png)

**Comment by eternalsky** [comment]
Done, 现在可以 fetchDataOnMount 为 false。
