### ISSUE TITLE
数组中的item为undefined时，会报错，看下是否要兼容这种情况

### ISSUE THREAD

**Issue by 2999** [uxcore/uxcore-select-form-field#9]
数组中的item为undefined时，会报错，看下是否要兼容这种情况

建议增加代码强壮性

https://github.com/uxcore/uxcore-select-form-field/blob/77bfe6da8f2a1ed2dbd49eebe610941b03caae0b/src/SelectFormField.jsx#L146

![default](https://user-images.githubusercontent.com/1653891/29757867-b8e129a4-8be1-11e7-8e55-92826be2cd5d.png)

**Comment by eternalsky** [comment]
Duplicate: https://github.com/uxcore/uxcore-select-form-field/issues/1
